// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectsMecsaSPA.Data;

#nullable disable

namespace ProjectsMecsaSPA.Migrations.Projects
{
    [DbContext(typeof(ProjectsDBContext))]
    [Migration("20240826162639_ProjectMigration")]
    partial class ProjectMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("LastEditionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("BillId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Commentary", b =>
                {
                    b.Property<int>("CommentaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentaryID"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("CommentaryID");

                    b.HasIndex("ProjectId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<long>("DNI")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            DNI = 1L,
                            Name = "Default",
                            Type = "Publico"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.FileModel", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"), 1L, 1);

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("FileId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CalculateBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequireOther")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSPAT")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSurgeProtector")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireTower")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiredDDCE")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiredLightningStrike")
                        .HasColumnType("bit");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Isfactured")
                        .HasColumnType("bit");

                    b.Property<string>("OC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OCDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TypeOfChange")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Ubication")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SellerId");

                    b.HasIndex("StateId");

                    b.HasIndex("TypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"), 1L, 1);

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SellerId");

                    b.ToTable("Seller");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            DNI = 0,
                            Email = "",
                            IsActive = false,
                            SellerName = "Sample"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderPriority")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            IsDeleted = false,
                            OrderPriority = 1,
                            StateName = "Pendiente"
                        },
                        new
                        {
                            StateId = 2,
                            IsDeleted = false,
                            OrderPriority = 2,
                            StateName = "Coordinado"
                        },
                        new
                        {
                            StateId = 3,
                            IsDeleted = false,
                            OrderPriority = 3,
                            StateName = "En ejecución"
                        },
                        new
                        {
                            StateId = 4,
                            IsDeleted = false,
                            OrderPriority = 4,
                            StateName = "Pendiente Informe"
                        },
                        new
                        {
                            StateId = 5,
                            IsDeleted = false,
                            OrderPriority = 5,
                            StateName = "Informe en proceso"
                        },
                        new
                        {
                            StateId = 6,
                            IsDeleted = false,
                            OrderPriority = 6,
                            StateName = "Ofertando"
                        },
                        new
                        {
                            StateId = 7,
                            IsDeleted = false,
                            OrderPriority = 7,
                            StateName = "Finalizado"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.TypeModel", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            IsDeleted = false,
                            Name = "No Establecido"
                        },
                        new
                        {
                            TypeId = 2,
                            IsDeleted = false,
                            Name = "Mantenimiento DDCE"
                        },
                        new
                        {
                            TypeId = 3,
                            IsDeleted = false,
                            Name = "Mantenimiento Ionizante"
                        },
                        new
                        {
                            TypeId = 4,
                            IsDeleted = false,
                            Name = "Mantenimiento Torre"
                        },
                        new
                        {
                            TypeId = 5,
                            IsDeleted = false,
                            Name = "Instalación DDCE"
                        },
                        new
                        {
                            TypeId = 6,
                            IsDeleted = false,
                            Name = "Instalación Ionizante"
                        },
                        new
                        {
                            TypeId = 7,
                            IsDeleted = false,
                            Name = "Instalación Torre"
                        },
                        new
                        {
                            TypeId = 8,
                            IsDeleted = false,
                            Name = "Instalación SPAT"
                        },
                        new
                        {
                            TypeId = 9,
                            IsDeleted = false,
                            Name = "Instalación Supresores"
                        },
                        new
                        {
                            TypeId = 10,
                            IsDeleted = false,
                            Name = "Certificación SPAT"
                        },
                        new
                        {
                            TypeId = 11,
                            IsDeleted = false,
                            Name = "Eléctricos"
                        },
                        new
                        {
                            TypeId = 12,
                            IsDeleted = false,
                            Name = "Otros"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Bill", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Project", "Project")
                        .WithMany("Bills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Commentary", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Project", "Project")
                        .WithMany("Commentaries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.FileModel", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Project", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.Seller", "Seller")
                        .WithMany("Projects")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.State", "State")
                        .WithMany("Projects")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.TypeModel", "Type")
                        .WithMany("Projects")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Seller");

                    b.Navigation("State");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Project", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Commentaries");

                    b.Navigation("Files");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Seller", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.State", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.TypeModel", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
