// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectsMecsaSPA.Data;

#nullable disable

namespace ProjectsMecsaSPA.Migrations.Projects
{
    [DbContext(typeof(ProjectsDBContext))]
    [Migration("20260116145035_initialDbProjects")]
    partial class initialDbProjects
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BillDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BillNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("DeletedReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastEditionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEditor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<int>("TaskNumber")
                        .HasColumnType("int");

                    b.HasKey("BillId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Bill");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.BillFile", b =>
                {
                    b.Property<int>("BillFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillFileId"), 1L, 1);

                    b.Property<string>("B24FileId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillFileId");

                    b.HasIndex("BillId");

                    b.ToTable("BillFiles");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Commentary", b =>
                {
                    b.Property<int>("CommentaryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentaryID"), 1L, 1);

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentaryText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("CommentaryID");

                    b.HasIndex("ProjectId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyId"), 1L, 1);

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CompanyId");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            CompanyId = 1,
                            CompanyName = "Default"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<long>("DNI")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            DNI = 1L,
                            Name = "Default",
                            Type = "Publico"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeviceId"), 1L, 1);

                    b.Property<string>("DeviceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.FileModel", b =>
                {
                    b.Property<int>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileId"), 1L, 1);

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("FileId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Lead", b =>
                {
                    b.Property<int>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadId"), 1L, 1);

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ContactedBySeller")
                        .HasColumnType("bit");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DealNumber")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadOriginId")
                        .HasColumnType("int");

                    b.Property<int>("LeadRequestId")
                        .HasColumnType("int");

                    b.Property<int>("LeadStateId")
                        .HasColumnType("int");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.Property<int>("Prioritized")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isCalled")
                        .HasColumnType("bit");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("LeadId");

                    b.HasIndex("LeadOriginId");

                    b.HasIndex("LeadRequestId");

                    b.HasIndex("LeadStateId");

                    b.HasIndex("SellerId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadNotes", b =>
                {
                    b.Property<int>("LeadNoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadNoteId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadNoteId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadNotes");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadOrigin", b =>
                {
                    b.Property<int>("LeadOriginId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadOriginId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LeadOriginName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadOriginId");

                    b.ToTable("LeadOrigins");

                    b.HasData(
                        new
                        {
                            LeadOriginId = 1,
                            IsDeleted = false,
                            LeadOriginName = "WhatsApp"
                        },
                        new
                        {
                            LeadOriginId = 2,
                            IsDeleted = false,
                            LeadOriginName = "Facebook"
                        },
                        new
                        {
                            LeadOriginId = 3,
                            IsDeleted = false,
                            LeadOriginName = "Instagram"
                        },
                        new
                        {
                            LeadOriginId = 4,
                            IsDeleted = false,
                            LeadOriginName = "Sitio Web"
                        },
                        new
                        {
                            LeadOriginId = 5,
                            IsDeleted = false,
                            LeadOriginName = "Llamada Telefónica"
                        },
                        new
                        {
                            LeadOriginId = 6,
                            IsDeleted = false,
                            LeadOriginName = "Correo Electrónico"
                        },
                        new
                        {
                            LeadOriginId = 7,
                            IsDeleted = false,
                            LeadOriginName = "Referencia / Recomendación"
                        },
                        new
                        {
                            LeadOriginId = 8,
                            IsDeleted = false,
                            LeadOriginName = "LinkedIn"
                        },
                        new
                        {
                            LeadOriginId = 9,
                            IsDeleted = false,
                            LeadOriginName = "Google Ads"
                        },
                        new
                        {
                            LeadOriginId = 10,
                            IsDeleted = false,
                            LeadOriginName = "Evento / Feria"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadRequest", b =>
                {
                    b.Property<int>("LeadRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadRequestId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RequestName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadRequestId");

                    b.ToTable("LeadsRequest");

                    b.HasData(
                        new
                        {
                            LeadRequestId = 1,
                            IsDeleted = false,
                            RequestName = "pararrayos"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadState", b =>
                {
                    b.Property<int>("LeadStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadStateId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("Priority")
                        .HasColumnType("bit");

                    b.HasKey("LeadStateId");

                    b.ToTable("LeadsState");

                    b.HasData(
                        new
                        {
                            LeadStateId = 1,
                            IsDeleted = false,
                            Name = "Atendido",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 2,
                            IsDeleted = false,
                            Name = "Nuevo",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 3,
                            IsDeleted = false,
                            Name = "Contactado",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 4,
                            IsDeleted = false,
                            Name = "En Seguimiento",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 5,
                            IsDeleted = false,
                            Name = "Cotización Enviada",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 6,
                            IsDeleted = false,
                            Name = "Negociación",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 7,
                            IsDeleted = false,
                            Name = "Ganado",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 8,
                            IsDeleted = false,
                            Name = "Perdido",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 9,
                            IsDeleted = false,
                            Name = "No Calificado",
                            Order = 0,
                            Priority = false
                        },
                        new
                        {
                            LeadStateId = 10,
                            IsDeleted = false,
                            Name = "Pendiente de Respuesta",
                            Order = 0,
                            Priority = false
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Offer", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("CalculateBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Creation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("RequireOther")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSPAT")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireSurgeProtector")
                        .HasColumnType("bit");

                    b.Property<bool>("RequireTower")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiredDDCE")
                        .HasColumnType("bit");

                    b.Property<bool>("RequiredLightningStrike")
                        .HasColumnType("bit");

                    b.Property<string>("Responsible")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsibleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OfferId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(15,3)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FolderIDB24")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("Isfactured")
                        .HasColumnType("bit");

                    b.Property<string>("OC")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("OCDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequiredCoordination")
                        .HasColumnType("bit");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("TAX")
                        .HasColumnType("int");

                    b.Property<string>("TaskNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("TypeOfChange")
                        .HasColumnType("decimal(15,3)");

                    b.Property<string>("Ubication")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SellerId");

                    b.HasIndex("StateId");

                    b.HasIndex("TypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.SchDev", b =>
                {
                    b.Property<int>("SchDevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchDevId"), 1L, 1);

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DeviceId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("SchDevId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Schedule_Device");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"), 1L, 1);

                    b.Property<string>("Car")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarPlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<int>("DependencyId")
                        .HasColumnType("int");

                    b.Property<bool>("Draft")
                        .HasColumnType("bit");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WeekendWork")
                        .HasColumnType("bit");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.SchEmpl", b =>
                {
                    b.Property<int>("SchEmplId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SchEmplId"), 1L, 1);

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("SchEmplId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("Schedule_Employee");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"), 1L, 1);

                    b.Property<int>("Bitrix24Id")
                        .HasColumnType("int");

                    b.Property<int>("DNI")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SellerId");

                    b.ToTable("Seller");

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            Bitrix24Id = 1,
                            DNI = 0,
                            Email = "",
                            IsActive = false,
                            PhoneNumber = "1234567890",
                            SellerName = "Sample"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderPriority")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StateId");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            StateId = 1,
                            IsDeleted = false,
                            OrderPriority = 1,
                            StateName = "Pendiente"
                        },
                        new
                        {
                            StateId = 2,
                            IsDeleted = false,
                            OrderPriority = 2,
                            StateName = "Coordinado"
                        },
                        new
                        {
                            StateId = 3,
                            IsDeleted = false,
                            OrderPriority = 3,
                            StateName = "En ejecución"
                        },
                        new
                        {
                            StateId = 4,
                            IsDeleted = false,
                            OrderPriority = 4,
                            StateName = "Pendiente Informe"
                        },
                        new
                        {
                            StateId = 5,
                            IsDeleted = false,
                            OrderPriority = 5,
                            StateName = "Informe en proceso"
                        },
                        new
                        {
                            StateId = 6,
                            IsDeleted = false,
                            OrderPriority = 6,
                            StateName = "Ofertando"
                        },
                        new
                        {
                            StateId = 7,
                            IsDeleted = false,
                            OrderPriority = 7,
                            StateName = "Finalizado"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.TypeModel", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"), 1L, 1);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TypeId");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            IsDeleted = false,
                            Name = "No Establecido"
                        },
                        new
                        {
                            TypeId = 2,
                            IsDeleted = false,
                            Name = "Mantenimiento DDCE"
                        },
                        new
                        {
                            TypeId = 3,
                            IsDeleted = false,
                            Name = "Mantenimiento Ionizante"
                        },
                        new
                        {
                            TypeId = 4,
                            IsDeleted = false,
                            Name = "Mantenimiento Torre"
                        },
                        new
                        {
                            TypeId = 5,
                            IsDeleted = false,
                            Name = "Instalación DDCE"
                        },
                        new
                        {
                            TypeId = 6,
                            IsDeleted = false,
                            Name = "Instalación Ionizante"
                        },
                        new
                        {
                            TypeId = 7,
                            IsDeleted = false,
                            Name = "Instalación Torre"
                        },
                        new
                        {
                            TypeId = 8,
                            IsDeleted = false,
                            Name = "Instalación SPAT"
                        },
                        new
                        {
                            TypeId = 9,
                            IsDeleted = false,
                            Name = "Instalación Supresores"
                        },
                        new
                        {
                            TypeId = 10,
                            IsDeleted = false,
                            Name = "Certificación SPAT"
                        },
                        new
                        {
                            TypeId = 11,
                            IsDeleted = false,
                            Name = "Eléctricos"
                        },
                        new
                        {
                            TypeId = 12,
                            IsDeleted = false,
                            Name = "Otros"
                        });
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Bill", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Project", "Project")
                        .WithMany("Bills")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.BillFile", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Bill", "Bill")
                        .WithMany("BillFiles")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Commentary", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Project", "Project")
                        .WithMany("Commentaries")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.FileModel", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Project", "Project")
                        .WithMany("Files")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Lead", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.LeadOrigin", "Origin")
                        .WithMany("Leads")
                        .HasForeignKey("LeadOriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.LeadRequest", "LeadRequest")
                        .WithMany("Leads")
                        .HasForeignKey("LeadRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.LeadState", "LeadState")
                        .WithMany("Leads")
                        .HasForeignKey("LeadStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.Seller", "Seller")
                        .WithMany("Leads")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeadRequest");

                    b.Navigation("LeadState");

                    b.Navigation("Origin");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadNotes", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Lead", "Lead")
                        .WithMany("Notes")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Project", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.Customer", "Customer")
                        .WithMany("Projects")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.Seller", "Seller")
                        .WithMany("Projects")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.State", "State")
                        .WithMany("Projects")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.TypeModel", "Type")
                        .WithMany("Projects")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Customer");

                    b.Navigation("Seller");

                    b.Navigation("State");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.SchDev", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Device", "Device")
                        .WithMany("SchDevs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.Schedule", "Schedule")
                        .WithMany("SchDevs")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Schedule", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Project", "Project")
                        .WithMany("Schedules")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.SchEmpl", b =>
                {
                    b.HasOne("ProjectsMecsaSPA.Model.Employee", "Employee")
                        .WithMany("SchEmpls")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectsMecsaSPA.Model.Schedule", "Schedule")
                        .WithMany("SchEmpls")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Bill", b =>
                {
                    b.Navigation("BillFiles");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Company", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Customer", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Device", b =>
                {
                    b.Navigation("SchDevs");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Employee", b =>
                {
                    b.Navigation("SchEmpls");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Lead", b =>
                {
                    b.Navigation("Notes");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadOrigin", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadRequest", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.LeadState", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Project", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Commentaries");

                    b.Navigation("Files");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Schedule", b =>
                {
                    b.Navigation("SchDevs");

                    b.Navigation("SchEmpls");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.Seller", b =>
                {
                    b.Navigation("Leads");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.State", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("ProjectsMecsaSPA.Model.TypeModel", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
